import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Vendored OCR worker/core/wasm-glue JS, written by `pnpm vendor:ocr`
    // (which runs at prebuild) -- regenerated build output, not source.
    // Mirrors the reason already recorded in .gitignore for this directory.
    "public/tesseract/**",
    // Git worktrees live inside the repo at .claude/worktrees/<name>/, so a
    // worktree that has been built carries its own .next/ and public/tesseract/
    // that the globs above do not match -- they are anchored at the repo root.
    // Without this, `pnpm lint` from the main checkout walks another
    // worktree's build output and reports its errors as this tree's.
    ".claude/**",
  ]),
  {
    // Vendored assistant-ui components, generated by `assistant-ui init` and
    // re-generated on upgrade. Linting them gates us on upstream's style
    // choices and any fix here would be overwritten anyway. Narrow the rules
    // rather than ignoring the files, so real breakage still surfaces.
    files: [
      "src/components/attachment.tsx",
      "src/components/file.tsx",
      "src/components/image.tsx",
      "src/components/reasoning.tsx",
      "src/components/thread.tsx",
    ],
    rules: {
      "react-hooks/refs": "off",
      "react-hooks/static-components": "off",
      "react-hooks/purity": "off",
      "react-hooks/set-state-in-effect": "off",
      "jsx-a11y/alt-text": "off",
      "@next/next/no-img-element": "off",
    },
  },
]);

export default eslintConfig;
